Introduction to Coroutines and Channels/01_Introduction.md

So from a conversation with Eugene Petrenko a while back, he was told to remove `you` as a pronoun in the tutorials he was creating, sometimes it is unavoidable, but this is the reason for all the removals of the word `you`.
He may be able to give more information on this, as I have followed his example since then but did not.

changes and proofread

---

Introduction to Coroutines and Channels/02_BlockingRequest.md

same deal, removing most of the `you` instances.

checked and proofread

---

Introduction to Coroutines and Channels/03_UsingCallbacks.md

mainly you == we
also:
line 33-34 -- not sure if this is still correct, as I am really not sure what it is saying?

reviewed and proofread

---

Introduction to Coroutines and Channels/04_Suspend.md

review and proofread

---

Introduction to Coroutines and Channels/06_StructuredConcurrency.md

second review

---

Introduction to Coroutines and Channels/04_Suspend.md

final read through to check nothing has slipped through.
Final review suggestions

minor text adjust final

---

Introduction to Coroutines and Channels/08_Channels.md

last read through, minor suggestions

final read through review

---

Introduction to Coroutines and Channels/05_Concurrency.md

minor suggestions added, final read through

last read-through for minor suggestions

---

Introduction to Coroutines and Channels/09_Testing.md

check through, with minor suggestions included

final pass through

---

Introduction to Kotlin Multiplatform/04_js.md

Proofread watson

---

Introduction to Kotlin Multiplatform/08_summary.md

suggestion and proofread ready for review

suggestions and proofread

---

Targeting iOS and Android with Kotlin Multiplatform/07_Summary.md

updated links about
- [Kotlin/Native interop with Swift and Objective-C](https://kotlinlang.org/docs/reference/native/objc_interop.html)
- [Kotlin/Native as an Apple Framework](https://kotlinlang.org/docs/tutorials/native/apple-framework.html)
- [Multiplatform projects](https://kotlinlang.org/docs/reference/multiplatform.html)
- [kotlinx.coroutines](https://github.com/Kotlin/kotlinx.coroutines/blob/master/README.md)

update links in next steps section

---

Targeting iOS and Android with Kotlin Multiplatform/04_UsingSharedCodeAndroid.md

Also improve code blocks, they are not rendered correctly on https://play.kotlinlang.org/hands-on/Targeting%20iOS%20and%20Android%20with%20Kotlin%20Multiplatform/04_UsingSharedCodeAndroid

Fix broken URL and image references

---

Building Web Applications with React and Kotlin JS/01_Introduction.md
Building Web Applications with React and Kotlin JS/02_Setting_up.md
Building Web Applications with React and Kotlin JS/04_Making_It_React.md
Building Web Applications with React and Kotlin JS/05_Working_Together_Composing_Components.md
Building Web Applications with React and Kotlin JS/07_Using_Packages_From_NPM.md
Building Web Applications with React and Kotlin JS/08_Using_an_External_REST_API.md
Building Web Applications with React and Kotlin JS/09_Deploying_to_Production.md
The State of Kotlin JS/02_Setting_up.md
The State of Kotlin JS/03_Our_First_Program.md
The State of Kotlin JS/04_Using_APIs.md
The State of Kotlin JS/05_Debugging_in_the_Browser.md
The State of Kotlin JS/07_Tests_and_Test_Runners.md

Hi Sebastian,
this PR fixes the links to your images.

fix broken image links

---

Building Web Applications with React and Kotlin JS/02_Setting_up.md
Building Web Applications with React and Kotlin JS/04_Making_It_React.md
Building Web Applications with React and Kotlin JS/06_More_Components.md
Building Web Applications with React and Kotlin JS/07_Using_Packages_From_NPM.md

Removes references to `EAP` in the tutorial.
Clarifies explanation on external declarations and ensures code style is consistent in snippets.

Kotlin/JS updates for 1.3.70

---

Introduction to Kotlin Native/03_CInteropDefinitionFile.md
Targeting iOS and Android with Kotlin Multiplatform/06_SettingUpKotlinFramework.md
The State of Kotlin JS/03_Our_First_Program.md

Fixes link to `Kotlin/Native interoperability`.

Fix broken links to kotlinlang.org

---

Building Web Applications with React and Kotlin JS/05_Working_Together_Composing_Components.md

Snippet has wrong classname and props type argument, should match this: https://github.com/kotlin-hands-on/web-app-react-kotlin-js-gradle/blob/965049e5659177c257cd759975eddf37c0347dd5/src/main/kotlin/VideoList.kt#L13

Fix code snippet

---

Building Web Applications with React and Kotlin JS/02_Setting_up.md
Building Web Applications with React and Kotlin JS/03_A_First_Static_Page.md
Building Web Applications with React and Kotlin JS/08_Using_an_External_REST_API.md

I have updated Kotlin and React to the latest stable version. Nothing breaks after testing.
Corresponding code update: https://github.com/kotlin-hands-on/web-app-react-kotlin-js-gradle/pull/1

Upgrade kotlin and reactjs.

---

Getting Started with Ktor/02_creating-the-project.md

The first paragraph of the guide has an incomplete sentence `we can also use...`.
So, I have added a very basic completion sentence, update/remove if not necessary.

fixed partially missing description.

---

Targeting iOS and Android with Kotlin Multiplatform/05_CreatingiOSApp.md

Fix typo in 05_CreatingiOSApp.md

---

Introduction to Coroutines and Channels/03_UsingCallbacks.md

I spotted this while reading; I'm new to Kotlin in general, so please let me know if there's a different process for submitting changes or a specific PR format I should adhere to.

Correct minor typo in Callbacks chapter

---

Full Stack Web App with Kotlin Multiplatform/01_Introduction.md

Aside from the minor downcasing of words after the colon, I'm fixing here a typo on the word _beneficial_.

Benefitial -> Beneficial and other styling changes

---

Building Web Applications with React and Kotlin JS/09_Deploying_to_Production.md

Before deploying, we need to add to the commit the newly created `static.json` file (together with the changes done to the Gradle configuration).

Add `git add` command before deploying.

---

Full Stack Web App with Kotlin Multiplatform/07_Deploying_to_the_Cloud.md

I'm not sure if this is what was intended with the sentence; I think the current version is not technically incorrect but I found it a little unclear and thought there was a typo.

Update wording to use verb instead of adverb.

---

Networking and Data Storage with Kotlin Multiplatfrom Mobile/08_Creating_the_Android_application.md

removed duplicate "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0" import

Remove duplicate implementation of swiperefreshlayout lib

---

Full Stack Web App with Kotlin Multiplatform/07_Deploying_to_the_Cloud.md

I was performing the tutorial and it wasn't working on the cloud service or locally.  The `.coroutine `was missing from the earlier steps.  If you look in the projects final branch, it does have the `.coroutine.`
https://github.com/kotlin-hands-on/jvm-js-fullstack/blob/final/src/jvmMain/kotlin/Server.kt

Update 07_Deploying_to_the_Cloud.md - Missing .coroutine causes database to no longer function.

---

Full Stack Web App with Kotlin Multiplatform/05_Building_the_Frontend.md

Remove duplicate words on the text

---

Kotlin Native Concurrency/03_Global.md

Fix file name

---

Networking and Data Storage with Kotlin Multiplatfrom Mobile/02_Creating_the_KMM_project.md

it's preferable to use main then master

Update branch name
